# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system_app', '0006_auto_20180222_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurent',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('Ready', 'Ready'), ('On the way', 'On the way'), ('Cooking', 'Cooking'), ('Delivered', 'Delivered')]),
        ),
    ]
