# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system_app', '0007_auto_20180222_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Ready', 'Ready'), ('Cooking', 'Cooking')], max_length=500),
        ),
    ]
